#!/bin/bash

usage() {
  echo "Usage: $0 <command>"
  echo
  echo "where <command> could be one of the following commands, depending"
  echo "on the development needs."
  echo
  echo ".:: BOSP Setup"
  echo "- setup         : intialize the source tree"
  echo "    This command is require just the first time to properly setup"
  echo "    the BOSP source tree"
  echo
  echo ".:: BOSP Configuration"
  echo "- boostrap      : bootstrap the building system"
  echo "    Setup the BOSP building system to track all the submodules"
  echo "    which expose a Kconf/bosp.mk pair"
  echo "- config        : configure a build"
  echo "    Start a configuration of the BOSP building system"
  echo
  echo ".:: BOSP Update"
  echo "- udpate-devel  : update the source tree to the last stable version"
  echo "    Setup the BOSP building system to track the most recent development version"
  echo "- update-stable : update the source tree to the most advanced development version"
  echo "    Setup the BOSP building system to track the most recent stable version"
  echo
  echo ".:: BOSP Status"
  echo "- status        : dump short status for each module"
  echo "- status-full   : dump detaild status for each module"
  exit 1
}

if [ $# -lt 1 ]; then
  usage
fi

message() {
  echo
  echo -e "\033[34m.:: $1\033[0m"
}

update() {
  git fetch
  git checkout -B bosp origin/bosp
  message "Updating all BOSP modules..."
  git submodule foreach git fetch
}

update() {
  message "Update BOSP main module..."
  git pull --prune
  message "Sync all BOSP tracked modules..."
  git submodule foreach git fetch --prune
}

case $1 in
setup)
  message "Setup BOSP building system..."
  git submodule init
  git submodule update
  git submodule foreach git fetch
  git submodule foreach git checkout -B bosp origin/bosp
  make bootstrap
  ;;
update-stable)
  update
  message "Switching all BOSP modules to stable [bosp] branch..."
  git submodule foreach git checkout -B bosp origin/bosp
  ;;
update-devel)
  update
  message "Switching all BOSP modules to the development [bosp-next] branch..."
  git submodule foreach git checkout -B bosp origin/bosp-next
  ;;
bootstrap)
  message "Bootstrapping BOSP building system..."
  make bootstrap
  ;;
config)
  message "Configuring BOSP building system..."
  make menuconfig
  ;;
status)
  message "Current BOSP modules configuration:"
  git submodule status
  ;;
status-full)
  message "Current BOSP modules full configuration:"
  git submodule foreach git status -uno
  ;;
*)
  usage
esac

echo
echo

