#!/bin/bash

usage() {
  echo "Usage: $0 <command>"
  echo
  echo "where <command> could be:"
  echo "- boostrap      : bootstrap the building system"
  echo "- config        : configure a build"
  echo "- setup         : intialize the source tree"
  echo "- status        : dump short status for each module"
  echo "- status-full   : dump detaild status for each module"
  echo "- udpate-devel  : update the source tree to the last stable version"
  echo "- update-stable : update the source tree to the most advanced development version"
  exit 1
}

if [ $# -lt 1 ]; then
  usage
fi

message() {
  echo
  echo -e "\033[34m.:: $1\033[0m"
}

update() {
  git fetch
  git checkout -B bosp origin/bosp
  message "Updating all BOSP modules..."
  git submodule foreach git fetch
}


case $1 in
setup)
  message "Setup BOSP building system..."
  git submodule init
  git submodule update
  git submodule foreach git checkout -B bosp origin/bosp
  make bootstrap
  ;;
update-stable)
  message "Switching all BOSP modules to stable [bosp] branch..."
  git submodule update
  git submodule foreach git checkout -B bosp origin/bosp
  ;;
update-devel)
  message "Switching all BOSP modules to the development [bosp-next] branch..."
  git submodule update
  git submodule foreach git checkout -B bosp origin/bosp-next
  ;;
bootstrap)
  message "Bootstrapping BOSP building system..."
  make bootstrap
  ;;
config)
  message "Configuring BOSP building system..."
  make menuconfig
  ;;
status)
  message "Current BOSP modules configuration:"
  git submodule status
  ;;
status-full)
  message "Current BOSP modules full configuration:"
  git submodule foreach git status -uno
  ;;
*)
  usage
esac

echo
echo

